/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      //  System.out.println(new App().getGreeting());
linkss<Integer> testN=new linkss<>();
//
Node node1=new Node<>(1);
//Node node2=new Node<>(2);
//Node node3=new Node<>(3);
//Node node4=new Node<>(4);
//
        testN.append(1);
testN.insert(5);
testN.printAll();
//System.out.println(testN.toString());


    }
}
